version: "3.8"

services:

  web:

    build: ./app

    container_name: nginx-volume-demo

    ports:
      - "8080:80"

    volumes:
      - website_data:/usr/share/nginx/html

volumes:

  website_data:
